management:
  endpoints:
    web:
      exposure:
        include: "*"


spring:
  datasource:

#    #mssql
#    username: ${db.username}
#    password: ${db.pass}
#    url: jdbc:sqlserver://${db.host}:${db.port};databaseName=${db.name}

#  postgresql
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    org:
      springframework:
        security: DEBUG


server:
  port: 8080


